"""Assemble the speed patches for the game's 3D engine into khvcemu/_swerve_blob.py (a development tool: needs
`pip install keystone-engine`; the emulator itself only reads the generated bytes). Patches:

  span    the span fill below (see "The game's 3D engine" paragraph)
  matinv  a memo cache in front of the engine's 4x4 matrix inversion (function at 0x0101376C): the same matrices are
          inverted over and over (about 365 calls per frame on about 430 distinct matrices), and one inversion costs
          about 4,000 guest instructions; a hit costs about 150. The key is all 17 input words, so a hit returns
          exactly what the original would have computed.
Tried and dropped (2026-10-06; tools/bench_state.py on the user's save states, 4 runs each, and the headless Island
scenes; every one drew identical frames):
  flat    the flat (untextured, shaded) span fill at 0x0100B18C rewritten whole, and
  tex     the textured span's inner loop at 0x0100E31C with the texture's constants hoisted out of the loop:
          2 to 4% fewer guest instructions, but no measurable change in speed (gain over no patches: a fight +12.6% with them against
          +12.8% without, Agrabah's lava +9.9% against +9.8%, a Castle room +29.8% against +30.1%).
  float   a shortcut for the soft-float reverse subtract with a zero operand: it added instructions overall.
  scanline setup and fmul/fadd fast paths: estimated under 2% each, not built.
Fewer instructions is not the same as faster: Unicorn's time goes largely into memory accesses and block
dispatch, which those loops still do. Their code was not kept (it was never committed).

The game's 3D engine (swv21brew.mod) spends about half of all guest instructions in one function, the per-pixel
span fill at 0x0100A8B4 (module offset 0xA8B4). It is generic: for every pixel it re-reads flag words from the
state structure, spills its working values to the stack and always works out a fourth (alpha buffer) channel.
Most spans use one combination: alpha blend mode 0x40, framebuffer write on, no alpha buffer. For exactly that
combination this patch runs a tighter loop that produces identical pixels. Anything else (and any module whose
function bytes differ from the known ones) falls back to the original code, which stays in place.

State structure fields read (all 32-bit, r0 = pointer): +4 y, +8 framebuffer, +0xC depth buffer, +0x10 x start,
+0xDC x end, +0x1C z, +0x38/+0x3C/+0x40/+0x44 R/G/B/A and +0x68/+0x6C/+0x70/+0x74 their per-pixel steps,
+0x4C z step, +0x258 flags (1 color write, 0x20 depth test, 0x40 depth write, 0x800 alpha buffer),
+0x25C alpha threshold, +0x260 alpha buffer base, +0x268 blend mode.

    python tools/gen_swerve_patch.py
"""
import hashlib
import os
import sys

from keystone import KS_ARCH_ARM, KS_MODE_ARM, Ks

MOD_BASE = 0x01000000
FUNC = 0x0100A8B4              # original function: 0x0100A8B4 .. 0x0100AC0C
FUNC_END = 0x0100AC0C
BLOB_OFFSET = 0x00200000       # where the new code is placed, relative to the module's load address
BLOB = MOD_BASE + BLOB_OFFSET


def loop(tag, dtest, dwrite):
    """One specialised pixel loop. Registers: r1 fb ptr, r2 depth ptr, r3 z, r4 R, r5 G, r6 B, r7 A, r8 count,
    r9 dither (1..3), r10 dest pixel, r11 alpha (0..254), r12 packed result, r0/lr scratch.
    Stack: [sp] struct ptr, +4 alpha threshold, +8 z step, +12/16/20/24 R/G/B/A steps."""
    t = tag
    out = [f"L{t}:", "ldr r0, [sp, #4]", "cmp r0, r7, asr #8", f"bgt N{t}"]
    if dtest or dwrite:
        out.append("mov r0, r3, asr #12")
    if dtest:
        out += ["ldrh lr, [r2]", "cmp lr, r0", f"blt N{t}"]
    if dwrite:
        out.append("strh r0, [r2]")
    out += ["cmp r7, #0xff00", f"bge O{t}",
            "ldrh r10, [r1]", "mov r11, r7, asr #8"]
    # blend each channel towards the destination pixel: d + (((src - d) * a) >> 8), then dither, clamp, pack
    out += ["and r0, r10, #0xf800", "sub lr, r4, r0", "mul lr, r11, lr", "add r0, r0, lr, asr #8",
            "add r0, r9, r0, asr #9", "mov r0, r0, asr #2", "cmp r0, #31", "movgt r0, #31", "bic r0, r0, r0, asr #31",
            "mov r12, r0, lsl #11"]
    out += ["mov r0, r10, lsl #5", "and r0, r0, #0xfc00", "sub lr, r5, r0", "mul lr, r11, lr", "add r0, r0, lr, asr #8",
            "add r0, r9, r0, asr #8", "mov r0, r0, asr #2", "cmp r0, #63", "movgt r0, #63", "bic r0, r0, r0, asr #31",
            "orr r12, r12, r0, lsl #5"]
    out += ["mov r0, r10, lsl #27", "mov r0, r0, lsr #16", "sub lr, r6, r0", "mul lr, r11, lr", "add r0, r0, lr, asr #8",
            "add r0, r9, r0, asr #9", "mov r0, r0, asr #2", "cmp r0, #31", "movgt r0, #31", "bic r0, r0, r0, asr #31",
            "orr r12, r12, r0", f"b S{t}"]
    # opaque pixel (alpha >= 0xFF00): the source color is used as it is
    out += [f"O{t}:",
            "add r0, r9, r4, asr #9", "mov r0, r0, asr #2", "cmp r0, #31", "movgt r0, #31", "bic r0, r0, r0, asr #31",
            "mov r12, r0, lsl #11",
            "add r0, r9, r5, asr #8", "mov r0, r0, asr #2", "cmp r0, #63", "movgt r0, #63", "bic r0, r0, r0, asr #31",
            "orr r12, r12, r0, lsl #5",
            "add r0, r9, r6, asr #9", "mov r0, r0, asr #2", "cmp r0, #31", "movgt r0, #31", "bic r0, r0, r0, asr #31",
            "orr r12, r12, r0",
            f"S{t}:", "strh r12, [r1]"]
    out += [f"N{t}:", "add r1, r1, #2", "add r2, r2, #2", "eor r9, r9, #2",
            "ldr r0, [sp, #8]", "add r3, r3, r0", "ldr r0, [sp, #12]", "add r4, r4, r0", "ldr r0, [sp, #16]", "add r5, r5, r0",
            "ldr r0, [sp, #20]", "add r6, r6, r0", "ldr r0, [sp, #24]", "add r7, r7, r0",
            "subs r8, r8, #1", f"bgt L{t}", "b EXIT"]
    return out


def source():
    s = [
        "FAST:",
        # conditions for the fast path; otherwise run the original (r0 and the scratch registers only)
        "ldr r1, [r0, #0x268]", "cmp r1, #0x40", "bne TRAMP",
        "ldr r1, [r0, #0x258]", "tst r1, #1", "beq TRAMP",
        "ldr r2, [r0, #0x260]", "cmp r2, #0", "beq OK", "tst r1, #0x800", "bne TRAMP",
        "OK:",
        "push {r4, r5, r6, r7, r8, r9, r10, r11, lr}", "sub sp, sp, #0x24", "str r0, [sp]",
        "ldr r10, [r0, #0x10]", "ldr r11, [r0, #4]", "and r11, r11, #1", "add r11, r11, #1", "and r12, r10, #1",
        "eor r9, r11, r12, lsl #1",
        "ldr r1, [r0, #8]", "add r1, r1, r10, lsl #1",
        "ldr r2, [r0, #0xc]", "add r2, r2, r10, lsl #1",
        "ldr r8, [r0, #0xdc]", "sub r8, r8, r10",
        "ldr r3, [r0, #0x1c]", "ldr r4, [r0, #0x38]", "ldr r5, [r0, #0x3c]", "ldr r6, [r0, #0x40]", "ldr r7, [r0, #0x44]",
        "ldr r10, [r0, #0x25c]", "str r10, [sp, #4]", "ldr r10, [r0, #0x4c]", "str r10, [sp, #8]",
        "ldr r10, [r0, #0x68]", "str r10, [sp, #12]", "ldr r10, [r0, #0x6c]", "str r10, [sp, #16]",
        "ldr r10, [r0, #0x70]", "str r10, [sp, #20]", "ldr r10, [r0, #0x74]", "str r10, [sp, #24]",
        "ldr r10, [r0, #0x258]", "and r10, r10, #0x60",
        "cmp r10, #0x60", "beq LA", "cmp r10, #0x20", "beq LB", "cmp r10, #0x40", "beq LC", "b LD",
    ]
    s += loop("A", True, True) + loop("B", True, False) + loop("C", False, True) + loop("D", False, False)
    s += ["EXIT:", "ldr r0, [sp]", "add sp, sp, #0x24", "pop {r4, r5, r6, r7, r8, r9, r10, r11, pc}",
          "TRAMP:", "push {r4, r5, r6, r7, r8, r9, r10, r11, lr}", f"b #{FUNC + 4:#x}"]
    return s



INV = 0x0101376C               # matrix inversion: int Invert(Matrix* m), 16 floats + a flag word, in place
INV_END = 0x01013A80
INV_BLOB_OFFSET = 0x00201000
INV_SLOTS_BITS = 12            # 4096 slots of 144 bytes: key (17 words), result (17 words), tag (0 empty, 1 failed, 2 ok)


def matinv_source():
    return [
        "INV:",
        # the original returns 1 at once for these flag values: do the same (bx lr keeps ARM/Thumb interworking)
        "ldr r1, [r0, #0x40]", "cmp r1, #0x20", "cmpne r1, #0x3f", "moveq r0, #1", "bxeq lr",
        "push {r4, r5, r6, r7, r8, r9, r10, r11, lr}",
        "mov r4, r0",
        "mov r11, #0x1000000", "orr r11, r11, #0x190", "orr r11, r11, #3",          # hash multiplier 0x01000193
        "mov r10, #0",
        "mov r1, r4",
        "ldmia r1!, {r2, r3, r5, r6, r7, r8, r9, r12}",
    ] + [f"mla r10, r11, r10, {r}" for r in ("r2", "r3", "r5", "r6", "r7", "r8", "r9", "r12")] + [
        "ldmia r1!, {r2, r3, r5, r6, r7, r8, r9, r12}",
    ] + [f"mla r10, r11, r10, {r}" for r in ("r2", "r3", "r5", "r6", "r7", "r8", "r9", "r12")] + [
        "ldr r2, [r1]", "mla r10, r11, r10, r2",
        # slot = table + (hash >> 20) * 144
        f"mov r1, r10, lsr #{32 - INV_SLOTS_BITS}", "add r5, r1, r1, lsl #3", "mov r5, r5, lsl #4",
        "adr r6, TABLE", "add r5, r5, r6",
        "ldr r1, [r5, #136]", "cmp r1, #0", "beq MISS",
        # all 17 words of the key must match
        "mov r1, r4", "mov r2, r5",
        "ldmia r1!, {r6, r7, r8, r9, r10}", "ldmia r2!, {r0, r3, r11, r12, lr}",
        "cmp r6, r0", "cmpeq r7, r3", "cmpeq r8, r11", "cmpeq r9, r12", "cmpeq r10, lr", "bne MISS",
        "ldmia r1!, {r6, r7, r8, r9, r10}", "ldmia r2!, {r0, r3, r11, r12, lr}",
        "cmp r6, r0", "cmpeq r7, r3", "cmpeq r8, r11", "cmpeq r9, r12", "cmpeq r10, lr", "bne MISS",
        "ldmia r1!, {r6, r7, r8, r9, r10}", "ldmia r2!, {r0, r3, r11, r12, lr}",
        "cmp r6, r0", "cmpeq r7, r3", "cmpeq r8, r11", "cmpeq r9, r12", "cmpeq r10, lr", "bne MISS",
        "ldmia r1!, {r6, r7}", "ldmia r2!, {r0, r3}", "cmp r6, r0", "cmpeq r7, r3", "bne MISS",
        # hit: r2 now points at the stored result
        "ldr r1, [r5, #136]", "cmp r1, #2", "bne HIT0",
        "mov r1, r4",
        "ldmia r2!, {r0, r3, r6, r7, r8, r9, r10, r11, r12}", "stmia r1!, {r0, r3, r6, r7, r8, r9, r10, r11, r12}",
        "ldmia r2!, {r0, r3, r6, r7, r8, r9, r10, r11}", "stmia r1!, {r0, r3, r6, r7, r8, r9, r10, r11}",
        "mov r0, #1", "pop {r4, r5, r6, r7, r8, r9, r10, r11, pc}",
        "HIT0:", "mov r0, #0", "pop {r4, r5, r6, r7, r8, r9, r10, r11, pc}",
        "MISS:",
        "mov r1, #0", "str r1, [r5, #136]",                                          # the slot is not valid while it is rewritten
        "mov r1, r4", "mov r2, r5",
        "ldmia r1!, {r0, r3, r6, r7, r8, r9, r10, r11, r12}", "stmia r2!, {r0, r3, r6, r7, r8, r9, r10, r11, r12}",
        "ldmia r1!, {r0, r3, r6, r7, r8, r9, r10, r11}", "stmia r2!, {r0, r3, r6, r7, r8, r9, r10, r11}",
        "mov r0, r4", "bl TRAMPINV",
        "cmp r0, #1", "bhi DONE",
        "moveq r1, #2", "movne r1, #1", "beq SAVE",
        "str r1, [r5, #136]", "b DONE",
        "SAVE:", "mov r1, r4", "add r2, r5, #68",
        "ldmia r1!, {r6, r7, r8, r9, r10, r11, r12, lr}", "stmia r2!, {r6, r7, r8, r9, r10, r11, r12, lr}",
        "ldmia r1!, {r6, r7, r8, r9, r10, r11, r12, lr}", "stmia r2!, {r6, r7, r8, r9, r10, r11, r12, lr}",
        "ldr r6, [r1]", "str r6, [r2]",
        "mov r1, #2", "str r1, [r5, #136]",
        "DONE:", "pop {r4, r5, r6, r7, r8, r9, r10, r11, pc}",
        "TRAMPINV:", "push {r0, r4, r5, r6, r7, r8, r9, r10, r11, lr}", f"b #{INV + 4:#x}",
        "TABLE:",
    ]


def label_offset(lines, label):
    """Byte offset of a label in assembled code (every instruction is 4 bytes)."""
    n = 0
    for line in lines:
        if line == label + ":":
            return n * 4
        if not line.endswith(":"):
            n += 1
    raise KeyError(label)


def assemble(lines, at):
    ks = Ks(KS_ARCH_ARM, KS_MODE_ARM)
    code, _ = ks.asm("\n".join(lines), at)
    return bytes(code)


def stub_for(function, blob_at):
    ks = Ks(KS_ARCH_ARM, KS_MODE_ARM)
    stub, _ = ks.asm(f"b #{blob_at:#x}", function)
    return bytes(stub)


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    mod = os.path.join(here, "mod", "14957", "swv21brew.mod")
    if not os.path.isfile(mod) and len(sys.argv) > 1:
        mod = sys.argv[1]
    data = open(mod, "rb").read()

    def original(a, b):
        return data[a - MOD_BASE:b - MOD_BASE]

    inv_blob = assemble(matinv_source(), MOD_BASE + INV_BLOB_OFFSET)
    patches = {
        "span": dict(check=(FUNC, FUNC_END), stubs=[(FUNC, 0)], blob_offset=BLOB_OFFSET, blob=assemble(source(), BLOB),
                     table_offset=0, table_size=0),
        # the cache table starts right after the code: that is where `adr r6, TABLE` points
        "matinv": dict(check=(INV, INV_END), stubs=[(INV, 0)], blob_offset=INV_BLOB_OFFSET, blob=inv_blob,
                       table_offset=INV_BLOB_OFFSET + len(inv_blob), table_size=144 << INV_SLOTS_BITS),
    }
    regions = sorted((p["blob_offset"], p["blob_offset"] + len(p["blob"])) for p in patches.values()) +         sorted((p["table_offset"], p["table_offset"] + p["table_size"]) for p in patches.values() if p["table_size"])
    regions.sort()
    for (a0, a1), (b0, b1) in zip(regions, regions[1:]):
        assert a1 <= b0, f"patch code/table regions overlap: {a0:#x}-{a1:#x} and {b0:#x}-{b1:#x}"
    lines = [
        '"""GENERATED by tools/gen_swerve_patch.py: do not edit. Machine code of the 3D engine speed patches (see',
        'khvcemu/swerve_patch.py) and the SHA-256 of the original code each one replaces."""',
        "",
        f'MODULE_SHA256 = "{hashlib.sha256(data).hexdigest()}"      # swv21brew.mod as a whole',
        "PATCHES = {",
    ]
    for name, p in patches.items():
        lo, hi = p["check"]
        orig = original(lo, hi)
        lines += [f'    "{name}": dict(',
                  f'        function_offset={lo - MOD_BASE:#x}, original_length={len(orig)},',
                  f'        original_sha256="{hashlib.sha256(orig).hexdigest()}",',
                  "        stubs=["]
        for addr, entry in p["stubs"]:
            first = original(addr, addr + 4)
            stub = stub_for(addr, MOD_BASE + p["blob_offset"] + entry)
            lines.append(f'            dict(offset={addr - MOD_BASE:#x}, original_first=bytes.fromhex("{first.hex()}"), '
                         f'stub=bytes.fromhex("{stub.hex()}")),')
        lines += ["        ],",
                  f'        blob_offset={p["blob_offset"]:#x}, table_offset={p["table_offset"]:#x}, table_size={p["table_size"]},',
                  "        blob=bytes.fromhex("]
        h = p["blob"].hex()
        for i in range(0, len(h), 96):
            lines.append(f'            "{h[i:i + 96]}"')
        lines += ["        )),"]
    lines.append("}")
    path = os.path.join(here, "khvcemu", "_swerve_blob.py")
    open(path, "w", newline="\n").write("\n".join(lines) + "\n")
    for name, p in patches.items():
        print(f"{name}: {len(p['blob'])} bytes of code")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
